using System;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using RecordSynthesisPatcher.Core;
using RecordSynthesisPatcher.Settings;

namespace RecordSynthesisPatcher;

public static class Program
{
    private static Lazy<PatcherSettings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "Record Synthesis Patcher.esp")
            .Run(args);
    }

    public static void RunPatch(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        new PatcherEngine(
            state,
            state.PatchMod,
            _settings.Value)
            .Run();
    }
}
 